# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message
from langbot_plugin.api.entities.builtin.provider import message as provider_message
from langbot_plugin.api.entities.builtin.provider import message
import logging
import base64
import easyocr
import os
import tempfile
import re

import inspect


class DefaultEventListener(EventListener):

    def __init__(self):
        super().__init__()
        self.logger = logging.getLogger('LangBot_OCR_Helper')

    async def initialize(self):
        await super().initialize()
        
        @self.handler(events.PersonNormalMessageReceived)
        @self.handler(events.GroupNormalMessageReceived)
        async def handle(event_context: context.EventContext):
            # 预加载easyocr模型
            try:
                reader = easyocr.Reader(['ch_sim', 'en'])
                self.logger.info("EasyOCR模型预加载成功")
            except Exception as e:
                self.logger.error(f'EasyOCR预加载失败: {str(e)}')
                return

            with tempfile.TemporaryDirectory(prefix="ocr_cache_") as temp_dir:
                self.logger.info(f"创建临时目录: {temp_dir}")
                
                image_paths = []
                ocr_results = []  # 存储OCR结果

                try:
                    self.logger.info("收到消息事件")
                    
                    # 获取事件对象
                    event = event_context.event
                    self.logger.info(f"事件类型: {type(event).__name__}")
                    
                    # 尝试获取message_chain
                    message_chain = None
                    if hasattr(event, 'message_chain'):
                        message_chain = event.message_chain
                        self.logger.info(f"成功获取message_chain: {message_chain}")
                    elif hasattr(event_context, 'message_chain'):
                        message_chain = event_context.message_chain
                        self.logger.info(f"从event_context获取message_chain: {message_chain}")
                    
                    # 如果获取到了message_chain
                    if message_chain:
                        text = str(message_chain)
                        self.logger.info(f"消息内容: {text}")
                        
                        # 获取所有图片元素
                        images = [component for component in message_chain if isinstance(component, platform_message.Image)]
                        if images:
                            self.logger.info(f"检测到{len(images)}张图片")
                            
                            # 处理每张图片
                            for i, image_element in enumerate(images):
                                self.logger.info(f"处理第{i+1}张图片")
                                
                                # 获取图片的base64数据
                                if hasattr(image_element, 'base64') and image_element.base64:
                                    image_base64 = image_element.base64
                                    self.logger.info(f"图片{i+1}的base64长度: {len(image_base64)}")

                                    try:
                                        # 解码base64并保存为图片文件
                                        if image_base64.startswith('data:image/'):
                                            # 找到base64,后面的部分
                                            prefix_end = image_base64.find('base64,')
                                            if prefix_end != -1:
                                                image_base64 = image_base64[prefix_end + 7:]  # 7是"base64,"的长度
                                        
                                        self.logger.info(f"清理后base64长度: {len(image_base64)}, 前50字符: {image_base64[:50]}")
                                        try:
                                            # 方法1：首先尝试标准解码
                                            image_data = base64.b64decode(image_base64)
                                        except Exception as e:
                                            # 方法2：如果失败，添加必要的=填充
                                            self.logger.info(f"标准解码失败，尝试修复: {str(e)}")
                                            padding = 4 - (len(image_base64) % 4)
                                            if padding != 4:
                                                image_base64 += '=' * padding
                                            image_data = base64.b64decode(image_base64)
                                        image_path = os.path.join(temp_dir, f"image_{i+1}.png")
                                        
                                        # 保存图片文件
                                        with open(image_path, 'wb') as f:
                                            f.write(image_data)
                                        
                                        self.logger.info(f"图片{i+1}已保存到: {image_path}")
                                        self.logger.info(f"图片{i+1}文件大小: {len(image_data)} bytes")
                                        
                                        # 添加到路径列表
                                        image_paths.append(image_path)
                                        
                                        # 进行OCR处理
                                        self.logger.info(f"开始OCR识别图片{i+1}")
                                        try:
                                            # 使用EasyOCR识别图片
                                            result = reader.readtext(image_path, detail=0)
                                            text_result = " ".join(result)
                                            
                                            self.logger.info(f"图片{i+1} OCR结果: {text_result}")
                                            ocr_results.append(f"第{i+1}张图片识别结果: {text_result}")
                                        except Exception as ocr_error:
                                            self.logger.error(f"OCR处理图片{i+1}时发生错误: {str(ocr_error)}")
                                            ocr_results.append(f"第{i+1}张图片识别失败: {str(ocr_error)}")
                                        
                                    except Exception as e:
                                        self.logger.error(f"保存图片{i+1}时发生错误: {str(e)}")
                                        ocr_results.append(f"第{i+1}张图片处理失败: {str(e)}")
                                        continue

                            # 如果有OCR结果，发送回复
                            if ocr_results:
                                reply_text = "OCR识别结果:\n" + "\n".join(ocr_results)                    
                                # 发送回复

                                event.user_message_alter = provider_message.ContentElement.from_text(reply_text)

                                # test_ce = provider_message.ContentElement.from_text("测试")
                                # self.logger.info(f"测试 ContentElement:")
                                # self.logger.info(f"  str(): {str(test_ce)}")
                                # self.logger.info(f"  repr(): {repr(test_ce)}")

                                # # 查看 Pydantic 序列化
                                # if hasattr(test_ce, 'model_dump_json'):
                                #     self.logger.info(f"  model_dump_json(): {test_ce.model_dump_json()}")
                                    
                                # # 检查是否有特殊序列化方法
                                # if hasattr(test_ce, '__getstate__'):
                                #     self.logger.info(f"  有 __getstate__ 方法")
                                # if hasattr(test_ce, '__reduce__'):
                                #     self.logger.info(f"  有 __reduce__ 方法")

                                # self.logger.info(event)

                                self.logger.info("OCR结果已发送")
                            else:
                                self.logger.info("没有OCR识别结果可发送")
                                
                        else:
                            self.logger.info("消息中没有图片")
                    else:
                        self.logger.warning("无法获取message_chain或text_message字段,或该消息不支持消息链,请联系开发者")
                            
                except Exception as e:
                    self.logger.error(f"处理消息时出错: {e}", exc_info=True)

            self.logger.info("所有临时文件已清理完毕")
